FROM python:3.12-slim-bookworm

RUN apt-get update \
    && apt-get install -y --no-install-recommends ffmpeg \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY main.py .
COPY src/ src/

ARG TELEGRAM_BOT_TOKEN=""
ARG OWNER_USER_ID=163177765
ARG STAR_PRICE=1
ARG BOT_MODE=polling
ARG WEBHOOK_URL=""
ARG WEBHOOK_SECRET=""
ARG MAX_VIDEO_SIZE_MB=50
ARG DOWNLOAD_TIMEOUT_SECONDS=120
ARG MAX_CONCURRENT_DOWNLOADS=3
ARG STORAGE_TYPE=local
ARG LOCAL_STORAGE_PATH=./downloads
ARG S3_BUCKET=""
ARG S3_REGION=us-east-1
ARG S3_ACCESS_KEY=""
ARG S3_SECRET_KEY=""
ARG FFMPEG_PATH=ffmpeg
ARG ENABLE_COMPRESSION=true
ARG INSTAGRAM_USERNAME=""
ARG INSTAGRAM_PASSWORD=""
ARG INSTAGRAM_VERIFICATION_CODE=""
ARG INSTAGRAM_SESSION_PATH=./data/instagram_session.json
ARG LOG_LEVEL=INFO

ENV TELEGRAM_BOT_TOKEN=$TELEGRAM_BOT_TOKEN \
    OWNER_USER_ID=$OWNER_USER_ID \
    STAR_PRICE=$STAR_PRICE \
    BOT_MODE=$BOT_MODE \
    WEBHOOK_URL=$WEBHOOK_URL \
    WEBHOOK_SECRET=$WEBHOOK_SECRET \
    MAX_VIDEO_SIZE_MB=$MAX_VIDEO_SIZE_MB \
    DOWNLOAD_TIMEOUT_SECONDS=$DOWNLOAD_TIMEOUT_SECONDS \
    MAX_CONCURRENT_DOWNLOADS=$MAX_CONCURRENT_DOWNLOADS \
    STORAGE_TYPE=$STORAGE_TYPE \
    LOCAL_STORAGE_PATH=$LOCAL_STORAGE_PATH \
    S3_BUCKET=$S3_BUCKET \
    S3_REGION=$S3_REGION \
    S3_ACCESS_KEY=$S3_ACCESS_KEY \
    S3_SECRET_KEY=$S3_SECRET_KEY \
    FFMPEG_PATH=$FFMPEG_PATH \
    ENABLE_COMPRESSION=$ENABLE_COMPRESSION \
    INSTAGRAM_USERNAME=$INSTAGRAM_USERNAME \
    INSTAGRAM_PASSWORD=$INSTAGRAM_PASSWORD \
    INSTAGRAM_VERIFICATION_CODE=$INSTAGRAM_VERIFICATION_CODE \
    INSTAGRAM_SESSION_PATH=$INSTAGRAM_SESSION_PATH \
    LOG_LEVEL=$LOG_LEVEL

RUN mkdir -p data downloads

CMD ["python", "main.py"]
